### ISSUE TITLE
Support BigTable

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-tui#41]
Add `~/.datafusion/table_providers/bigtable.json` which stores configuration options to create `TableProvider` and add optional `BigTable` feature.  Tables defined in `bigtable.json` are loaded at startup.

Config fields comes from the below plus a table name field.
```
let bigtable_datasource = BigtableDataSource::new(
    "emulator".to_owned(),                               // project
    "dev".to_owned(),                                    // instance
    "weather_balloons".to_owned(),                       // table
    "measurements".to_owned(),                           // column family
    vec!["_row_key".to_owned()],                         // table_partition_cols
    "#".to_owned(),                                      // table_partition_separator
    vec![Field::new("pressure", DataType::Utf8, false)], // qualifiers
    true,                                                // only_read_latest
).await.unwrap();
```

**Comment by jychen7** [comment]
yes, that sounds good

**Comment by matthewmturner** [comment]
@jychen7 i started working on this, can you provide more info on the Qualifiers field and choosing the correct DataType for it?

**Comment by jychen7** [comment]
yes, due to Bigtabke limitation, only int64 and utf8 are supported, here is the example
https://github.com/datafusion-contrib/datafusion-bigtable/blob/63e7e128a3a29d98c64ab549876dbf0d178ecb9b/src/datasource.rs#L532

here is python script to that inserts data
https://github.com/datafusion-contrib/datafusion-bigtable/blob/63e7e128a3a29d98c64ab549876dbf0d178ecb9b/script/insert_rows.py#L10

**Comment by matthewmturner** [comment]
ok, so easy parsing logic then. if string then  DataType:Utf8 and if number then DataType:Int64. thx.

**Comment by matthewmturner** [comment]
@jychen7 one more question, will nullable always be false?

**Comment by jychen7** [comment]
thanks for raising this up. Ideally, every qualifier is nullable, but currently `datafusion-bigtable` will error if more than (>=) two qualifiers' cell value are null. So please force `nullable=false` for now

**Comment by matthewmturner** [comment]
Ok - sounds good. Thanks.
