### ISSUE TITLE
Editor navigation/usage issues

### ISSUE THREAD

**Issue by seryj** [datafusion-contrib/datafusion-tui#49]
First of all, thanks for creating and working on this project! A good graphical interface will definitely help a lot of people in the future!

Now, to my issues. While playing around, there were several situations when the application crashed/or behaved wrongly/not-expected in the editor window. 

Crashes:
1. When using non-ascii characters (like German "umlaut" character ä, ö, ü), the application crashes when such a character is deleted. The issue is that non-ascii chars consume more then 1 byte but currently all operations in the editor directly change the bytes inside of the string (Lines) object.  
2. When the editor is opened and there is no text inside, moving the cursor crashes the application.

Wrong behavior:
1. When typing a character inside a line, the character appears in the end of the line. (I think this one was already fixed)

Usability issues:
1. In the end of the line, when moving a cursor to the right, the cursor stays in the same line instead of jumping to the next one
2. In the beginning of a line, when moving a cursor to the left the cursor stays in the same line instead of jumping to the previous one
3. End/Home buttons do not work

While all issues except for non-ascii handling are not that big, handling non-ascii characters requires a re-implementation of almost all functions of the Editor object because direct changing of a byte inside the String object does not work anymore and one has to use Chars instead. 

This being said, I can offer an PR where above mentioned issues are addressed and appropriate unit tests are provided. But of course only if contribution to this project is desired. Alternatively, I could provide an PR with unit tests only. Whatever you prefer.

Best regards

**Comment by matthewmturner** [comment]
Hi @seryj! Thanks so much for the report.

Yes, i definitely agree the application still crashes more than it should.  I am very glad to have someone else using it so i can find out more when these issues happen :)  thank you again for raising.

Can you confirm you are on latest master?  I am making updates frequently - often related to crashes (in particular driven from editor).  For example, i fixed the issue on moving cursor panics when no text is present and correctly typing characters inside a line.

I am definitely very happy to accept PRs, in particular with unit tests.  Adding tests are currently on my to-do list but i havent had chance to work on them yet.

Let me know if any other issues are of interest to you - im happy to reprioritize my efforts where others see value.  my next big focus will likely be on #39 which i think can add a lot of value.

thanks again.

**Comment by seryj** [comment]
Hi  @matthewmturner , 

thanks for your quick reply! I indeed did not test the latest version of the code - you are really quick integrating new features. :) 
I prepared a PR with some unit tests in the hope that they will help. I think, I will wait a little bit with a PR for handling non-ascii characters because it looks like that you are currently reorganizing the code quite a bit and a probability for a conflict is quite high at the moment. And maybe you will fix everything by yourself - quick as you are. :D

And no need to re-prioritize your work - I'm sure you know better what is more important! I just was curious how the new UI for Datafusion will look like and wanted to help a little bit. 

Regarding unit tests which you mentioned: if you create a short document with things which you would like to test first, I could try to take over some of the tasks.

Best

**Comment by matthewmturner** [comment]
Thank you @seryj - very helpful!

Yes - there is definitely a bit of reorganization going on. The next piece is likely #47 which will make it easier to add new tabs and allow the project to be more extensible.  After that, I'm hoping the core / editor will be at least somewhat stable.

The help is definitely appreciated - i didnt think anyone was really using yet 😅 

To the extent you continue using it and can find / report bugs or features i will definitely prioritize getting those fixed / added.  Thats basically how im driving my own prioritization list (im trying to make it my interactive data analysis tool of choice).

I can also definitely work on documenting some test ideas.  getting more done there would be super valuable.
