### ISSUE TITLE
Add commands in normal mode to scroll faster

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-tui#56]
j and k perhaps, taking influence from vim

**Comment by matthewmturner** [comment]
also h an l to scroll left and right by column (which will require storing column widths)

**Comment by seryj** [comment]
As a vim user, I like the idea very much :)  On the other side, j, k, h and l in vim are also only moving one character/line. Why not use the "usual" keys (home, end, screen up, screen down...) for faster navigation? Don't you think, it'll be more natural for most users?

**Comment by matthewmturner** [comment]
indeed, i think you are right. i was being a little lazy and trying not to look into managing a new Key type (in particular for key combinations).  But it will be better to just do it right.  I will think on this a bit more.

**Comment by seryj** [comment]
Oh, is it really a new Key type? I thought you can just add Key::PageDown, Key::PageUp, ... in "edit_mode_handler"? Or is it what you mean?

**Comment by matthewmturner** [comment]
I was using "Type" loosely, you are correct.  Ive just been somewhat scarred from implementing all the logic for key handling (i just finished making a number of significant improvements for newline, backspace, and scrolling - perhaps you could test it out?).  

I had also been considering using something like what vim has where you can prefix h,j,k,l with a number as a modifier to it (i.e. 5j for 5 rows down) so it wasnt so drastic as going to the extremes with home / end - and i considered that a new "type" as well.  But page up / down may be a simpler solution.  I've also been holding off on this as i want to freeze the column names when scrolling down but havent been able to give thought on the right way to do that yet.  ill need to play with the tui widgets some more.

**Comment by seryj** [comment]
Are you by chance familiar with a tool called k9s (https://github.com/derailed/k9s)? It's a tool for managing Kubernetes clusters in a shell via UI and has an interesting feature: when one needs to update configuration files of an object, it opens the configuration file in Vim. At least on my machine. I assume that depending on the EDITOR env variable, other editors will be opened. 
Why am I writing this: if one could achieve the same in your tool - i.e. when the user presses "e", the pre-configured editor application is opened in the editor tab, this could make development of the editor tab much easier as soon as initial complexities (like integrating another editor application, getting information when this application is closed, etc.) are solved. Things like syntax highlighting, auto completion, advanced editing, etc. are then there for free (if the editor application supports these features) and this can significantly increase user-experience. 

I mean, I have no idea if this is possible at all and if yes, this will probably require a loooot of efforts for investigation and implementation. But it would be cool. :) 

What do you think? If you are not completely against it, I can google a little bit and try to find out if this is possible.

**Comment by matthewmturner** [comment]
This would be super interesting and indeed it would be fantastic to outsource key logic.  that being said this is likely a significant undertaking - i will likely focus on current priorities i have in mind which are the following:

1 => 0.1 release
2 => `ApiTableProvider`
3 => Multiple tabs
4 => Exposing more meta data / object store info

If you could look into the feasibility of this that would be super cool.

perhaps one option is starting with something like helix (https://github.com/helix-editor/helix) - i started using this recently.  Given its written in rust theres a chance it might be a tiny bit easier to integrate and not having to worry about connecting to different editor environments.
