### ISSUE TITLE
Testing Overview

### ISSUE THREAD

**Issue by matthewmturner** [datafusion-contrib/datafusion-tui#62]
- **Editor**: The idea is to test different inputs that can be received from user while in `Edit` mode of a SQL Editor and ensure that the `Input` reflects these inputs.  It is very context dependent.  For example different keys have different expected behavior depending on where they are on the editor (i.e. you cant go up a row when already on the top row).
  - The function `edit_mode_handler` has all supported keys.  Look at these keys and coming up with the attendant tests is a good place to start.
  - The correct handling of scrolling will also need to be tested.  This happens when cursor is moving at end of block and ensuring the correct text is shown.
  - A second priority could be ensuring navigation between tabs is handled correctly
  - Key inputs can be done on `Input` directly but also, and its probably better, on `Key` events.
- **Context**: This involves testing that queries and their results are properly integrated back into the app.  I.e. if a successful query is executed then it should generate `QueryResult` with the appropriate `QueryResultMeta` data.
  - Test successful and unsuccessful queries to ensure results handled appropriately
- **Configuration**: the `.datafusion` directory is critical in making `dft` a powerful and reproducible tool for data analysis.  It has the `.datafusion/.datafusionrc` file for DDL and the `.datafusion/object_stores` and `.datafusion/table_providers` for extending the core with custom data sources (i.e. S3, Bigtable, HTTP APIs).  These extensions will often be feature gated.
  - Having tests that create dummy versions of the relevant files and ensuring that they either load the relevant data source or error correctly is needed. 
  - **UI** - Test that drawing UI components returns the correct output, in particular in the context of errors.

We should add some test data to the repo to enable testing queries in CI

**Comment by seryj** [comment]
Hi, the tab with this Issue is opened in my browser since 5 days or so... but I just did not manage to start implementation. :-/ 

Which part is the most critical/important? I will not manage to do a lot this week but I could at least start doing something  and extend the tests next week after bank holidays.

**Comment by matthewmturner** [comment]
No worries at all - and no pressure if you're busy. Honestly just having you as a sounding board on ideas is a huge value. 

I think a good way to proceed if you can would be you focusing on editor testing and edge cases. I think you're already familiar with that setup already and have an idea of how things "should work". 

Then I can focus on the execution context and configuration testing.

**Comment by seryj** [comment]
Sounds good for me, I will then continue with the editor part. I also think that this is the part where I can contribute at most. But unfortunately not this week anymore - have to finish some tasks for the job. :-( 

Not sure when Eastern is celebrated in US, but to be on the safe side - happy Eastern! :)

**Comment by matthewmturner** [comment]
Great - thanks much for the help!

and thank you (it is this weekend), Happy Easter to you as well!

**Comment by matthewmturner** [comment]
also FYI im going to put testing utilities in `utils/test_util.rs` if you need to do the same.

**Comment by matthewmturner** [comment]
@seryj hope you are feeling better and everything going well with family.

I've been a bit busy lately as well although i did start a [PR](https://github.com/datafusion-contrib/datafusion-tui/pull/80) for testing query handling.  

im also working adding functionality for using [azure](https://github.com/datafusion-contrib/datafusion-objectstore-azure) as an objectstore and the work that resulted from that (mainly related to getting all dependencies to use the same version of datafusion).  with my current availability my guess is that i wouldnt be able to start looking into something else for another week or so in the most optimistic case.  i will ping you then if you havent started so you know im looking to work on editor testing and we can coordinate if needed.

thanks again for your support on this :)
